version: '3.8'

services:
  server:
    image: library-back-dev
    build:
      context: ./backend # The context will pick this directory as the "build context"
      dockerfile: dev.Dockerfile # This will simply tell which dockerfile to read
    volumes:
      - ./backend:/usr/src/app # The path can be relative, so ./ is enough to say "the same location as the docker-compose.yml"
    ports:
      - 3001:3001
    container_name: library-back-dev # This will name the container hello-front-dev
  # mongo:
  #   container_name: library-back-dev-mongo
  #   image: mongo:latest
  #   ports:
  #    - 27017:27017
  #   environment:
  #     MONGO_INITDB_DATABASE: the_database
  #   volumes: 
  #     - ./backend/mongo_data:/data/db
  app:
    image: patient-front-dev
    build:
      context: ./frontend # The context will pick this directory as the "build context"
      dockerfile: dev.Dockerfile # This will simply tell which dockerfile to read
    volumes:
      - ./frontend:/usr/src/app # The path can be relative, so ./ is enough to say "the same location as the docker-compose.yml"
    ports:
      - 3000:3000
    container_name: patient-front-dev # This will name the container hello-front-dev
