version: '3.8'

services:
  server:
    image: prod-library-back-dev2
    build:
      context: . # The context will pick this directory as the "build context"
      dockerfile: Dockerfile # This will simply tell which dockerfile to read
    volumes:
      - ./:/usr/src/app # The path can be relative, so ./ is enough to say "the same location as the docker-compose.yml"
    ports:
      - 3000:3000
    container_name: prod-library-back-dev2 # This will name the container hello-front-dev
